### ISSUE TITLE
[PE-D] There is no way to undo a done command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#175]
It is possible that the user enters the wrong index.

Based on the UG it doesnt seem that there is any way to undo this.

![image.png](https://raw.githubusercontent.com/nwhloo99/ped/main/files/f82ed819-e1de-4baf-ba66-681074fc7932.png)

Entering the done command tells the user that the event is already marked as done. There is nothing wrong with this, it just might be better to have some way to undo this.

![image.png](https://raw.githubusercontent.com/nwhloo99/ped/main/files/4b63d19b-d0c9-48ca-a5e8-30f898c1b90f.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: nwhloo99/ped#4

**Comment by XXJJXJ** [comment]
Wont fix due to v1.4 contraints
