### ISSUE TITLE
[PE-D] Redundancy of Sort function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#179]
There is currently no other way to sort the events other than by time. Should this sorting not be inherent (whenever I add a event, it should be sorted already without me using sortEvents)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: benedictchuajj/ped#7

**Comment by XXJJXJ** [comment]
Wont fix due to v1.4 contraints
