### ISSUE TITLE
[PE-D] Incorrect example in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#197]
In the command summary table, the editEvent command example is missing an INDEX

![image.png](https://raw.githubusercontent.com/nwhloo99/ped/main/files/f53563a2-7a3c-4972-87dd-f097cea576f3.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: nwhloo99/ped#9

**Comment by XXJJXJ** [comment]
Fixed in #213
