### ISSUE TITLE
[PE-D] Suggestion for UI

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#200]
Since there already is a view command to look at a Participant's info, it might be better to put less info in the Participant card in the UI. Otherwise it might make the view command slightly redundant. Also this might help to make your UI look better, as Participant cards can start to look quite cluttered 

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: nwhloo99/ped#10

**Comment by XXJJXJ** [comment]
Not fixing
