### ISSUE TITLE
[PE-D] Suggestion: Partial string matching for find command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#205]
![Screenshot 2021-10-29 at 5.23.55 PM.png](https://raw.githubusercontent.com/benedictchuajj/ped/main/files/a3771f75-03a6-47c2-a778-5e7941bc24a0.png)

In the screenshot above, a user might want to find all events hosted by NUS and might search for it using `findEvent nus`. However, this only returns the first event in this list as current searching is done by exact word matching. Might not be useful enough for a user in this scenario.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: benedictchuajj/ped#18

**Comment by XXJJXJ** [comment]
Wont fix due to v1.4 contraints
