### ISSUE TITLE
[PE-D] Participants can still be added even if an event is done

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-T10-2/tp#208]
### Steps to reproduce
1. `done 1`
2. `enroll 2 1`

### Expected
Should not be able to add a participants after an event is done. (up to the team if you guys think this make sense)

### Screenshot
![image.png](https://raw.githubusercontent.com/phuccuongngo99/ped/main/files/af9aaf64-9ecc-4065-86e2-31e6d1f02b7c.png)

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: phuccuongngo99/ped#12

**Comment by XXJJXJ** [comment]
Wont fix in v1.4
