### ISSUE TITLE
Potential UG bugs (Feel free to add on/verify)

### ISSUE THREAD

**Issue by XXJJXJ** [AY2122S1-CS2103T-T10-2/tp#223]
UG bugs:

- [x] typo in `view` command last example. Should not be 'delete 1' should be 'view 1'. **(Changed in my branch)**
- [x] DeleteNok Participant_ID or PARTICIPANT_INDEX? -- consistency with Command Summary & `enroll` and `expel` command. Standardise to one format **(Changed in my branch)**
- [x] Sequence of showParticipants in Command Summary different from rest of the document (_Not v.important_)**(Changed in my branch)**
- [x] Add [Coming soon] Section for `UndoneCommand` and other disclaimers (Pls add on)
Undo event
Event Time Period
Detect schedule clashes for participants

**Comment by ntwbruce** [comment]
Let me know if anything is unclear, for the typos quoted a section of that line only so it might not be clear which line I'm referring to.

General
- [ ] Update all photos: Events with no participants display "0 participant", now updated to "0 participants"
- [ ] Ensure all bullet points have full stops at the end (most do, so I think easier to just standardise to including full stops)
 
Introduction
- [ ] "Managera is OS-independent, meaning it will..."
- [ ] "any operating system. (Windows, MacOS, Linux)" --> "any operating system (Windows, MacOS, Linux)." (move full stop)

Quick start
- [ ] Maybe explain where to find the JAR file on the GitHub releases page (for those who never use GitHub before), also explain what a home folder is
- [ ] `delete` `3` --> `delete 3`

Participant
- [ ] "Edit a Participants" --> "Edit a Participant's details"
- [ ] "Add **a** Next-of-Kin to a Participant"
- [ ] "Delete **a** Next-of-Kin of a Participant"

add
- [ ] Standardise "Participant" to capital P
- [ ] "(The new participant will be added.)" (add full stop)

edit
- [ ] Standardise "Participant" to capital P
- [ ] "If a participant is edited in a way..." The line break is weird

find
- [ ] Clarify what an `OR` search is (or just rephrase to make clearer)
- [ ] "with the name "John"; possible matches:..." --> "with the name "John". Some possible matches are..." 

addNok
- [ ] "Adding **a** Next-of-Kin to a Participant: `addNok`"
- [ ] Janette --> Jannette

deleteNok
- [ ] "Deleting **a** Next-of-Kin of a Participant: `deleteNok`"

Event
- [ ] "Show Participants of an Event" --> "List the Participants of an Event"

addEvent
- [ ] "24-hr format e.g., 0000 to 2359" --> "24-hr format, i.e. 0000 to 2359"
- [ ] "20th November 2021 **at** 9:00am"

editEvent
- [ ] "24-hr format e.g., 0000 to 2359" --> "24-hr format, i.e. 0000 to 2359"

findEvent
- [ ] Clarify what an `OR` search is (or just rephrase to make clearer)
- [ ] "with the name "party"; possible matches:..." --> "with the name "party". Some possible matches are..." 

filterEvents
- [ ] "24-hr format e.g., 0000 to 2359" --> "24-hr format, i.e. 0000 to 2359"
- [ ] "18th September 2021 **at 9:00**am"

Valid emails
- [ ] "The domain must" points should flow like one continuous sentence (all the points have comma at the end, and the last one has a full stop). Like the one under Event or Participant that lists all the commands.
